### ISSUE TITLE
show testcases with errors or exceptions

### ISSUE THREAD

**Issue by AlexHaxe** [emilyst/vscode-test-explorer-diagnostics#1]
Gratz on your new extension!

It looks like your extension only shows diagnostics for failed tests and not for errored tests (I know it's fresh out of the factory, and you might already have plans for these errors). 
Would be nice if they showed up as diagnostics as well.
![20200519_TestExplorerDiagnostics](https://user-images.githubusercontent.com/7204032/82340809-f1221e80-99ef-11ea-9156-ffe6d459bd98.png)

I'm undecided if skipped testcases should show up in diagnostics.

**Comment by emilyst** [comment]
Great idea. Handling different test states is absolutely something I need to do. Thanks for bringing it here!

**Comment by emilyst** [comment]
Can you see if version 0.1.0 (being published now) resolves this issue for you?

**Comment by AlexHaxe** [comment]
yes, new version solves it:
![20200523_TestExplorerDiagnostics](https://user-images.githubusercontent.com/7204032/82726197-abf93780-9ce2-11ea-9d60-613eed2cc9aa.png)

thanks!
