### ISSUE TITLE
support of tool-specific diagnostics

### ISSUE THREAD

**Issue by EighthMayer** [emilyst/vscode-test-explorer-diagnostics#2]
Thank you very much for your work, Emily! By coincedence this extension solves one of problems I have with my personal project. I've thought to make something similar myself, and it's really nice that I can focus on other tasks instead. Thank you very much indeed.

Would be nice if extension could also adress diagnostics specific for used unit-testing tool. It is especially useful for errored tests because, as I see it, error of test is an inherently tool-specific state. But it would be useful for other outcomes as well - tool can report warnings even if test passed.

Let me explain my use case: I work with ceedling test adapter (C language) and tests could be errored (currently they reported as failed, but I'm planning to fix it) if code syntax is wrong or if compilation or linking failed. Also I can get warnings if code is considered wrong but compiles anyway. All of these problems reported from used toolchain (GCC in my case) to stderr, which is then could be passed in TestEvent message field - as I understood from comment above this field it's intended for this exact purpose - reporting of problems.

VSC already has a mechanism for parsing such tool-specific problems - Tasks with problemMatchers. It's regex-based - output of tool is just scanned with regular expressions to find problems information - file, line, etc. Unfortunately it seems like it's not usable in this case (at least I've not figured a way to use it) - problemMatchers-related code is not accessible directly from extensions and Tasks are not not suitable because tool could be executed multiple times when running test suites - problems reported by Task would be cleared before each execution.

So, as I see it, the most proper way of implementing this would be to copy implementation of problemMatchers from VSC source code (it's in problemMatcher.ts file) to extension and make it configurable from extension settings. Algorithm is something like "if there is problem-matching patterns defined in extension settings, search for them in message field of every TestEvent and report diagnostics accordingly".

Now, why I think this should be in this extension rather than in tool-specific test adapters. First, adapters are not necessarily tool-specific - I use Ceedling tool, but I can swap underlying compiler and messages would be different. Second - if test adapters were handling their diagnostics themselves, this extension would not be needed, but it is - so it's only logical to implement this feature here.

Sorry for wall of text and thanks for your time. I intend to contribute btw.

**Comment by emilyst** [comment]
Hi! Thanks for filing an issue! I'll try to address your points inline below.

> Thank you very much for your work, Emily! By coincedence this extension solves one of problems I have with my personal project. I've thought to make something similar myself, and it's really nice that I can focus on other tasks instead. Thank you very much indeed.

I'm so glad this work has been able to help you!

> Would be nice if extension could also adress diagnostics specific for used unit-testing tool. It is especially useful for errored tests because, as I see it, error of test is an inherently tool-specific state. But it would be useful for other outcomes as well - tool can report warnings even if test passed.

This sounds like it duplicates #1. Can you confirm?

I intend to expand the kinds of diagnostics available not just on test failures, but on tests passing, warnings, errors, and the like. I alluded to this in the README when I said, "Add preferences for which severity of diagnostics to provide." But I recognize this was unclear.
 
> Let me explain my use case: I work with ceedling test adapter (C language) and tests could be errored (currently they reported as failed, but I'm planning to fix it) if code syntax is wrong or if compilation or linking failed. Also I can get warnings if code is considered wrong but compiles anyway. All of these problems reported from used toolchain (GCC in my case) to stderr, which is then could be passed in TestEvent message field - as I understood from comment above this field it's intended for this exact purpose - reporting of problems.

Yep. This sounds right.

> VSC already has a mechanism for parsing such tool-specific problems - Tasks with problemMatchers. It's regex-based - output of tool is just scanned with regular expressions to find problems information - file, line, etc. Unfortunately it seems like it's not usable in this case (at least I've not figured a way to use it) - problemMatchers-related code is not accessible directly from extensions and Tasks are not not suitable because tool could be executed multiple times when running test suites - problems reported by Task would be cleared before each execution.

I considered using a problem matcher initially, but I realized that the Test Explorer extension isn't actually a task with output, so I had to write this extension you see here.

> So, as I see it, the most proper way of implementing this would be to copy implementation of problemMatchers from VSC source code (it's in problemMatcher.ts file) to extension and make it configurable from extension settings. Algorithm is something like "if there is problem-matching patterns defined in extension settings, search for them in message field of every TestEvent and report diagnostics accordingly".
> 
> Now, why I think this should be in this extension rather than in tool-specific test adapters. First, adapters are not necessarily tool-specific - I use Ceedling tool, but I can swap underlying compiler and messages would be different. Second - if test adapters were handling their diagnostics themselves, this extension would not be needed, but it is - so it's only logical to implement this feature here.

I think I see what you're getting at, but let me make sure by re-summarizing.

You believe that it would be appropriate for this extension to look at each test event it sees and—based on the output message contained in the test event—determine the correct diagnostic to populate, if any.

I can see the merit of this idea, but this seems like an explosion of scope for this extension. I more or less am relying on the test adapters to report test events with the states I need. You can see [a full list of the current possible test event states here](https://github.com/hbenl/vscode-test-adapter-api/blob/105f6b453e9900a10549e4e60c6d74e84a9fee14/src/index.ts#L287).

Here's the division of responsibilities, roughly.

* The Test Explorer extension is responsible for providing a UI and a platform for the test adapters.
* The test adapters are responsible for bridging the gap between the Test Explorer UI and the actual project you're working on. It knows how to run tests, and it understands their output and is responsible for emitting the correct events to populate the UI.
* The test controllers interact with adapters to provide new functionality on top of them which isn't specific to any particular project or language.

It seems clear to me that the _adapters_ are the portion most directly responsible for understanding what's actually happening on a given test run, and the _controllers_ merely add new functionality based on the events they see.

For that reason, it seems inappropriate for this extension to cut across into parsing the actual output text. That seems like a concern for the adapter, which would then issue the correct test event state ("failed," "skipped," "errored," or what have you). Then I can map these states to [the most appropriate DiagnosticSeverity](https://code.visualstudio.com/api/references/vscode-api#DiagnosticSeverity)—`Information`, `Hint`, `Warning`, or `Error`.

As I see it, what I'd like to do is two things. First, I'd like to implement the appropriate mappings. I hardcoded the error severity only for now, but I know I wanted the other things. [That was suggested in the thread in which this extension was originally proposed.](https://github.com/hbenl/vscode-test-explorer/issues/136#issuecomment-629918126)

Second, I'd like to provide the option of which kinds of these diagnostics you'd actually like to see. I haven't provided any settings for this extension yet, but this is my intent soon. (No need to populate thousands of diagnostics stating a test passed unless the user really wants that.)

> Sorry for wall of text and thanks for your time. I intend to contribute btw.

Thanks to you as well for participating! Filing this issue _is_ a contribution.

**Comment by emilyst** [comment]
Can you see if version 0.1.0 (being published now) resolves this issue for you?

**Comment by EighthMayer** [comment]
> This sounds like it duplicates #1. Can you confirm?
> Can you see if version 0.1.0 (being published now) resolves this issue for you?

Um, no... I was talking about parsing TestEvent message (if it's provided) with regular expressions to extract (possibly multiple) errors/warnings of used testing tool and emitting diagnostics.

> I can see the merit of this idea, but this seems like an explosion of scope for this extension.

Okay perhaps what I've came up with is needlessly complicated - "one size fits all" solutions tend to never be good ones. Perhaps the simplest way to get what I need is indeed just handle diagnostics in adapter.

Thank you for your time!

**Comment by emilyst** [comment]
> > This sounds like it duplicates #1. Can you confirm?
> > Can you see if version 0.1.0 (being published now) resolves this issue for you?
> 
> Um, no... I was talking about parsing TestEvent message (if it's provided) with regular expressions to extract (possibly multiple) errors/warnings of used testing tool and emitting diagnostics.

I see. It seems as if what's intended here is for a test adapter to emit a test event with [multiple decorations](https://github.com/hbenl/vscode-test-adapter-api/blob/105f6b453e9900a10549e4e60c6d74e84a9fee14/src/index.ts#L295-L299). I haven't finished support for this yet (see #3).

> > I can see the merit of this idea, but this seems like an explosion of scope for this extension.
> 
> Okay perhaps what I've came up with is needlessly complicated - "one size fits all" solutions tend to never be good ones. Perhaps the simplest way to get what I need is indeed just handle diagnostics in adapter.

If you create your own diagnostics, you'll be incompatible with this extension (since there will be slightly differing duplicate diagnostics). Your call to make on whether to do that.

> Thank you for your time!

**Comment by EighthMayer** [comment]
> It seems as if what's intended here is for a test adapter to emit a test event with multiple decorations.

Yes, it seems better than emitting diagnostics from adapter, didn't think about that. Thank you.
